name: Build sillyGirl

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Git clone sillyGirl
      run:
        git clone https://github.com/cdle/sillyGirl.git /home/runner/go/src/github.com/cdle/sillyGirl

    - name: Git clone cable
      run:
        cd /home/runner/go/src/github.com/cdle/sillyGirl/
        mkdir develop && cd develop && git clone https://github.com/cdle/jd_price.git
        pwd
        ls -l
    
    - name: Git clone boltdb
      run:
        cd develop && git clone https://${{ secrets.CABLE_TOKEN }}@github.com/cdle/boltdb.git
        
    - name: Git clone qinglong
      run:
        cd develop && git clone https://${{ secrets.CABLE_TOKEN }}@github.com/cdle/qinglong.git
        
    - name: Git clone jd_price
      run:
        cd develop && git clone https://github.com/cdle/jd_price.git
        
    - name: Git clone jd_cookie
      run:
        cd develop && git clone https://${{ secrets.CHESS }}@github.com/ufuckee/jd_cookie.git
        
    - name: Create dev.go
      run:
        mv dev.go.demo dev.go

    - name: Push to binary
      run: |
        n=$(date +%s%3N)
        echo "package core" > core/compile_time.go
        echo "var compiled_at = \"$n\"" >> core/compile_time.go
        GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o sillyGirl_linux_arm64
        //GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o sillyGirl_linux_amd64
        //GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o sillyGirl_windows_amd64.exe
        mkdir -p /opt/images
        sudo mv -f sillyGirl_linux_amd64 /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: sillyGirl-packages
        path: /opt/images/
       
